[coverage:run]
branch = True

[coverage:report]
show_missing = True
exclude_lines =
    raise NotImplementedError
    return NotImplemented
    def __repr__
omit = test_*

[pytest]
addopts =
    --strict -p no:cacheprovider --showlocals